shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver

packages:
  - apps/*
  - packages/*

patchedDependencies:
  '@msw/data': patches/@msw__data.patch

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msw: true
  vue-demi: true
