openapi: 3.1.0

info:
  title: API Schemas
  version: '1.0'

components:
  schemas:
    Err:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Err'
