// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetTodosData, GetTodosErrors, GetTodosResponses, PostTodosData, PostTodosErrors, PostTodosResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getTodos = <ThrowOnError extends boolean = true>(options: Options<GetTodosData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTodosResponses, GetTodosErrors, ThrowOnError>({
        url: '/todos',
        ...options
    });
};

export const postTodos = <ThrowOnError extends boolean = true>(options: Options<PostTodosData, ThrowOnError>) => {
    return (options.client ?? client).post<PostTodosResponses, PostTodosErrors, ThrowOnError>({
        url: '/todos',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
