// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteTodoByIdData, GetTodoByIdData, GetTodoByIdResponses, GetTodosData, GetTodosResponses, PostTodosData, PostTodosResponses, UpdateTodoByIdData, UpdateTodoByIdResponses } from './types.gen';
import { vGetTodoByIdResponse, vGetTodosResponse, vPostTodosResponse, vUpdateTodoByIdResponse } from './valibot.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getTodos = <ThrowOnError extends boolean = true>(options: Options<GetTodosData, ThrowOnError>) => (options.client ?? client).get<GetTodosResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGetTodosResponse, data),
    url: '/todos',
    ...options
});

export const postTodos = <ThrowOnError extends boolean = true>(options: Options<PostTodosData, ThrowOnError>) => (options.client ?? client).post<PostTodosResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vPostTodosResponse, data),
    url: '/todos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteTodoById = <ThrowOnError extends boolean = true>(options: Options<DeleteTodoByIdData, ThrowOnError>) => (options.client ?? client).delete<unknown, unknown, ThrowOnError>({ url: '/todos/{id}', ...options });

export const getTodoById = <ThrowOnError extends boolean = true>(options: Options<GetTodoByIdData, ThrowOnError>) => (options.client ?? client).get<GetTodoByIdResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGetTodoByIdResponse, data),
    url: '/todos/{id}',
    ...options
});

export const updateTodoById = <ThrowOnError extends boolean = true>(options: Options<UpdateTodoByIdData, ThrowOnError>) => (options.client ?? client).patch<UpdateTodoByIdResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vUpdateTodoByIdResponse, data),
    url: '/todos/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
