// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Todo = {
    readonly id: string;
    title: string;
    status: TodoStatus;
};

export const TodoStatus = {
    ACTIVE: 'Active',
    CANCELLED: 'Cancelled',
    PAUSED: 'Paused',
    COMPLETED: 'Completed'
} as const;

export type TodoStatus = typeof TodoStatus[keyof typeof TodoStatus];

export type TodoWritable = {
    title: string;
    status: TodoStatus;
};

export type GetTodosData = {
    body?: never;
    path?: never;
    query: {
        start: number;
        limit: number;
    };
    url: '/todos';
};

export type GetTodosResponses = {
    /**
     * Get todos
     */
    200: {
        data: Array<Todo>;
        total: number;
    };
};

export type GetTodosResponse = GetTodosResponses[keyof GetTodosResponses];

export type PostTodosData = {
    body: TodoWritable;
    path?: never;
    query?: never;
    url: '/todos';
};

export type PostTodosResponses = {
    /**
     * Create todo
     */
    200: Todo;
};

export type PostTodosResponse = PostTodosResponses[keyof PostTodosResponses];

export type DeleteTodoByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type GetTodoByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type GetTodoByIdResponses = {
    /**
     * Get todo by id
     */
    200: Todo;
};

export type GetTodoByIdResponse = GetTodoByIdResponses[keyof GetTodoByIdResponses];

export type UpdateTodoByIdData = {
    body: TodoWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type UpdateTodoByIdResponses = {
    /**
     * Update todo by id
     */
    200: Todo;
};

export type UpdateTodoByIdResponse = UpdateTodoByIdResponses[keyof UpdateTodoByIdResponses];
