// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TodoItem = {
    readonly id: string;
    title: string;
    status: TodoStatus;
};

export const TodoStatus = {
    ACTIVE: 'Active',
    CANCELLED: 'Cancelled',
    PAUSED: 'Paused',
    COMPLETED: 'Completed'
} as const;

export type TodoStatus = typeof TodoStatus[keyof typeof TodoStatus];

export type ApiErr = {
    code: string;
    message: string;
};

export type TodoItemWritable = {
    title: string;
    status: TodoStatus;
};

export type GetTodosData = {
    body?: never;
    path?: never;
    query: {
        start: number;
        limit: number;
    };
    url: '/todos';
};

export type GetTodosErrors = {
    /**
     * Bad request
     */
    400: ApiErr;
};

export type GetTodosError = GetTodosErrors[keyof GetTodosErrors];

export type GetTodosResponses = {
    /**
     * Get todos
     */
    200: {
        data: Array<TodoItem>;
        total: number;
    };
};

export type GetTodosResponse = GetTodosResponses[keyof GetTodosResponses];

export type PostTodosData = {
    body: TodoItemWritable;
    path?: never;
    query?: never;
    url: '/todos';
};

export type PostTodosErrors = {
    /**
     * Bad request
     */
    400: ApiErr;
};

export type PostTodosError = PostTodosErrors[keyof PostTodosErrors];

export type PostTodosResponses = {
    /**
     * Create todo
     */
    200: TodoItem;
};

export type PostTodosResponse = PostTodosResponses[keyof PostTodosResponses];
