// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vTodoStatus = v.picklist([
    'Active',
    'Cancelled',
    'Paused',
    'Completed'
]);

export const vTodoItem = v.object({
    id: v.pipe(v.pipe(v.string(), v.uuid()), v.readonly()),
    title: v.pipe(v.string(), v.maxLength(200)),
    status: vTodoStatus
});

export const vApiErr = v.object({
    code: v.string(),
    message: v.string()
});

export const vTodoItemWritable = v.object({
    title: v.pipe(v.string(), v.maxLength(200)),
    status: vTodoStatus
});
