// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vTodoStatus = v.picklist([
    'Active',
    'Cancelled',
    'Paused',
    'Completed'
]);

export const vTodo = v.object({
    id: v.pipe(v.pipe(v.string(), v.uuid()), v.readonly()),
    title: v.pipe(v.string(), v.maxLength(200)),
    status: vTodoStatus
});

export const vApiErr = v.object({
    code: v.string(),
    message: v.string()
});

export const vTodoWritable = v.object({
    title: v.pipe(v.string(), v.maxLength(200)),
    status: vTodoStatus
});

/**
 * Get todos
 */
export const vGetTodosResponse = v.object({
    data: v.array(vTodo),
    total: v.number()
});

/**
 * Create todo
 */
export const vPostTodosResponse = vTodo;

/**
 * Get todo by id
 */
export const vGetTodoByIdResponse = vTodo;

/**
 * Update todo by id
 */
export const vUpdateTodoByIdResponse = vTodo;
